### ISSUE TITLE
Bug in sum function

### ISSUE THREAD

**Issue by HylkeB** [Planeshifter/kernel-smooth#1]
There is a bug in the sum function (found in kernel.js, line number 43).

Original code:
```javascript
sum = function(arr){
  var ret = 0;
  for(var i = 0; i < arr.length; i++){
  }    
    ret += arr[i];
  return ret;
};
```

Code that fixes it:
```javascript
sum = function(arr){
  var ret = 0;
  for(var i = 0; i < arr.length; i++){
    ret += arr[i];
  }
  return ret;
};
```

Unfortunately im quite new to github, but its an easy fix (this bug made the example fail).

**Comment by Planeshifter** [comment]
Thank you very much for notifying me! I fixed the bug and uploaded a new version of the package to npm.  In cases where you spot a bug and fix it yourself, it is also possible to create a pull request to merge the bug fixes into the master branch of the git project.
Best wishes,
Philipp
